name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write
  contents: read
  packages: read 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JFROG_CLI_LOG_LEVEL: DEBUG
      PLATFORM_REPO: 'davidle-npm'
      BUILD_NAME: 'test'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://davidle123test.jfrog.io
        with:
          oidc-provider-name: davidle-poc
          oidc-audience: github

      - name: Set CLI Config
        # This creates the .npmrc with Artifactory credentials via OIDC
        run: jf npm-config --repo-resolve=${{ env.PLATFORM_REPO }}
        working-directory: ./package

      - name: Append GitHub Scoped Registry
        # We add the second registry. 'npm install' will now see both.
        run: |
          npm config set @davidle-jfrog:registry https://npm.pkg.github.com
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' >> .npmrc
        working-directory: ./package

      - name: Verify Config
        run: cat .npmrc
        working-directory: ./package
           
      - name: Install Dependencies
        # Using standard npm so our .npmrc isn't deleted/replaced during the run
        run: npm install
        working-directory: ./package
         
      - name: Collect and Publish Build Info
        run: |
          # 1. Capture environment variables
          jf rt build-collect-env ${{ env.BUILD_NAME }} ${{ github.run_number }}
          
          # 2. Scan the directory to add dependencies to the build record
          # This replaces the automatic collection usually done by 'jf npm install'
          jf rt build-add-dependencies ${{ env.BUILD_NAME }} ${{ github.run_number }} --path=./package
          
          # 3. Upload the build-info to Artifactory
          jf rt build-publish ${{ env.BUILD_NAME }} ${{ github.run_number }}
