name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write
  contents: read
  packages: read 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JFROG_CLI_LOG_LEVEL: DEBUG
      PLATFORM_REPO: 'davidle-npm' # This must be the Virtual Repo containing your GitHub Remote
      BUILD_NAME: 'test'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://davidle123test.jfrog.io
        with:
          oidc-provider-name: davidle-poc
          oidc-audience: github

      - name: Set CLI Config
        # Points only to the Virtual Repo; Artifactory handles the GitHub routing
        run: jf npm-config --repo-resolve=${{ env.PLATFORM_REPO }}
        working-directory: ./package

      - name: Install and Collect Build Info
        # Using the JFrog wrapper is now the "happy path" since there is only one registry URL
        # This automatically collects dependencies and environment variables
        run: |
          rm -f package-lock.json
          jf npm install --build-name=${{ env.BUILD_NAME }} --build-number=${{ github.run_number }}
        working-directory: ./package

      - name: Publish Build Info
        # Uploads the metadata that was automatically captured in the previous step
        run: |
          jf rt build-publish ${{ env.BUILD_NAME }} ${{ github.run_number }}
        working-directory: ./package
