name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write
  contents: read
  packages: read 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JFROG_CLI_LOG_LEVEL: DEBUG
      PLATFORM_REPO: 'davidle-npm'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://davidle123test.jfrog.io
        with:
          oidc-provider-name: davidle-poc
          oidc-audience: github

      - name: Set CLI Config
        # We run this INSIDE the ./package directory
        run: jf npm-config --repo-resolve=${{ env.PLATFORM_REPO }} --repo-deploy=${{ env.PLATFORM_REPO }}
        working-directory: ./package

      - name: Append GitHub Scoped Registry
        # We append to the .npmrc INSIDE the ./package directory
        run: |
          echo '@davidle-jfrog:registry=https://npm.pkg.github.com' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' >> .npmrc
        working-directory: ./package

      - name: Verify Config
        run: cat .npmrc
        working-directory: ./package
           
      - name: Install Dependencies
        # jf npm install now finds the package.json right next to it
        run: jf npm install --build-name=test --build-number=${{ github.run_number }}
        working-directory: ./package
         
      - name: Publish Build info
        run: |
          jf rt build-collect-env test ${{ github.run_number }}
          jf rt build-publish test ${{ github.run_number }}
